version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    working_dir: /app
    ports:
      - "8000:8000"
    command: npm run dev
    volumes:
      - ./src:/app/src
    environment:
      PORT: 8000
